begin;

create extension if not exists pgcrypto;

create type public.user_role as enum ('mahasiswa', 'dosen', 'admin');
create type public.account_status as enum ('active', 'inactive');
create type public.publication_status as enum ('draft', 'published');
create type public.group_type as enum ('Gymnospermae', 'Angiospermae');
create type public.cotyledon_type as enum ('Monokotil', 'Dikotil', 'Tidak Berlaku');
create type public.taxon_rank as enum ('kingdom', 'divisi', 'kelas', 'ordo', 'famili', 'genus', 'spesies');
create type public.media_type as enum ('image', 'diagram', 'video');
create type public.quiz_type as enum ('pilihan_ganda', 'esai', 'campuran', 'pretest', 'practice', 'posttest');
create type public.question_type as enum ('pilihan_ganda', 'esai', 'multiple_choice', 'true_false');

create table public.app_settings (
  key text primary key,
  value text not null,
  updated_at timestamptz not null default now()
);

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  role public.user_role not null default 'mahasiswa',
  institution text,
  status public.account_status not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.plant_species (
  id bigint generated by default as identity primary key,
  code text not null unique,
  slug text not null unique,
  local_name text not null,
  scientific_name text not null,
  author_name text,
  group_type public.group_type not null,
  cotyledon_type public.cotyledon_type not null,
  description text,
  habitat text,
  benefits text,
  image_path text,
  status public.publication_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.taxa (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.taxa(id) on delete set null,
  name text not null,
  rank public.taxon_rank not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (rank, name)
);

create table public.species_taxa (
  species_id bigint not null references public.plant_species(id) on delete cascade,
  taxon_id bigint not null references public.taxa(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (species_id, taxon_id)
);

create table public.morphologies (
  species_id bigint primary key references public.plant_species(id) on delete cascade,
  root text,
  stem text,
  leaf text,
  flower text,
  fruit text,
  seed text,
  special_characteristics text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.physiologies (
  species_id bigint primary key references public.plant_species(id) on delete cascade,
  reproduction text,
  growth text,
  adaptation text,
  additional_information text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.locations (
  id bigint generated by default as identity primary key,
  location_name text not null,
  village text,
  district text not null,
  regency text not null,
  province text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (district, regency, province)
);

create table public.plant_observations (
  id bigint generated by default as identity primary key,
  species_id bigint not null references public.plant_species(id) on delete cascade,
  location_id bigint not null references public.locations(id) on delete cascade,
  observer_id uuid references public.profiles(id) on delete set null,
  observation_date date,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (species_id, location_id)
);

create table public.media (
  id bigint generated by default as identity primary key,
  species_id bigint references public.plant_species(id) on delete cascade,
  observation_id bigint references public.plant_observations(id) on delete cascade,
  filename text not null,
  file_path text not null,
  media_type public.media_type not null default 'image',
  caption text,
  is_primary boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (species_id is not null or observation_id is not null),
  unique (species_id, file_path)
);

create table public.learning_modules (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text not null unique,
  description text not null default '',
  module_order integer not null default 1 check (module_order > 0),
  estimated_minutes integer not null default 0 check (estimated_minutes >= 0),
  chapter_summary jsonb not null default '[]'::jsonb,
  source_file text,
  status public.publication_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (module_order)
);

create table public.learning_lessons (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.learning_modules(id) on delete cascade,
  source_id text unique,
  title text not null,
  slug text not null,
  content text not null,
  content_format text not null default 'markdown',
  key_points jsonb not null default '[]'::jsonb,
  source_sections jsonb not null default '[]'::jsonb,
  lesson_order integer not null default 1 check (lesson_order > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (module_id, slug),
  unique (module_id, lesson_order)
);

create table public.module_species (
  module_id bigint not null references public.learning_modules(id) on delete cascade,
  species_id bigint not null references public.plant_species(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (module_id, species_id)
);

create table public.quizzes (
  id bigint generated by default as identity primary key,
  module_id bigint not null references public.learning_modules(id) on delete cascade,
  title text not null,
  quiz_type public.quiz_type not null default 'pilihan_ganda',
  passing_score integer not null default 60 check (passing_score between 0 and 100),
  duration integer not null default 30 check (duration between 1 and 360),
  status public.publication_status not null default 'published',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  question_text text not null,
  question_type public.question_type not null default 'pilihan_ganda',
  score_weight integer not null default 1 check (score_weight between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.question_options (
  id bigint generated by default as identity primary key,
  question_id bigint not null references public.questions(id) on delete cascade,
  option_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.question_keys (
  question_id bigint primary key references public.questions(id) on delete cascade,
  correct_option_id bigint not null references public.question_options(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.quiz_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  quiz_id bigint not null references public.quizzes(id) on delete cascade,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  score integer check (score between 0 and 100),
  total_correct integer not null default 0 check (total_correct >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index quiz_attempts_one_active_idx
  on public.quiz_attempts (user_id, quiz_id)
  where completed_at is null;

create table public.quiz_answers (
  id bigint generated by default as identity primary key,
  attempt_id bigint not null references public.quiz_attempts(id) on delete cascade,
  question_id bigint not null references public.questions(id) on delete cascade,
  selected_option_id bigint references public.question_options(id) on delete set null,
  essay_answer text,
  is_correct boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (attempt_id, question_id)
);

create index plant_species_catalog_idx on public.plant_species (status, group_type, cotyledon_type, local_name);
create index taxa_rank_name_idx on public.taxa (rank, name);
create index plant_observations_species_idx on public.plant_observations (species_id, observation_date desc);
create index learning_lessons_module_idx on public.learning_lessons (module_id, lesson_order);
create index quizzes_module_idx on public.quizzes (module_id, status);
create index questions_quiz_idx on public.questions (quiz_id);
create index quiz_attempts_user_idx on public.quiz_attempts (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'app_settings', 'profiles', 'plant_species', 'taxa', 'morphologies',
    'physiologies', 'locations', 'plant_observations', 'media',
    'learning_modules', 'learning_lessons', 'quizzes', 'questions',
    'question_options', 'question_keys', 'quiz_attempts', 'quiz_answers'
  ]
  loop
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, name, email, institution)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(coalesce(new.email, ''), '@', 1)),
    coalesce(new.email, ''),
    nullif(trim(new.raw_user_meta_data ->> 'institution'), '')
  )
  on conflict (id) do update
  set email = excluded.email,
      updated_at = now();
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert or update of email on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, name, email, institution)
select
  id,
  coalesce(nullif(trim(raw_user_meta_data ->> 'name'), ''), split_part(coalesce(email, ''), '@', 1)),
  coalesce(email, ''),
  nullif(trim(raw_user_meta_data ->> 'institution'), '')
from auth.users
on conflict (id) do nothing;

create or replace function public.current_user_role()
returns public.user_role
language sql
stable
security definer
set search_path = public
as $$
  select role
  from public.profiles
  where id = auth.uid() and status = 'active'
$$;

create or replace function public.can_manage_content()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() in ('admin', 'dosen'), false)
$$;

revoke all on function public.current_user_role() from public;
revoke all on function public.can_manage_content() from public;
grant execute on function public.current_user_role() to anon, authenticated;
grant execute on function public.can_manage_content() to anon, authenticated;

alter table public.app_settings enable row level security;
alter table public.profiles enable row level security;
alter table public.plant_species enable row level security;
alter table public.taxa enable row level security;
alter table public.species_taxa enable row level security;
alter table public.morphologies enable row level security;
alter table public.physiologies enable row level security;
alter table public.locations enable row level security;
alter table public.plant_observations enable row level security;
alter table public.media enable row level security;
alter table public.learning_modules enable row level security;
alter table public.learning_lessons enable row level security;
alter table public.module_species enable row level security;
alter table public.quizzes enable row level security;
alter table public.questions enable row level security;
alter table public.question_options enable row level security;
alter table public.question_keys enable row level security;
alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;

create policy "Managers can read app settings" on public.app_settings
  for select to authenticated using (public.can_manage_content());
create policy "Storage bucket setting is public" on public.app_settings
  for select to anon, authenticated using (key = 'storage_bucket');

create policy "Users can read their profile and managers can read all" on public.profiles
  for select to authenticated
  using (id = auth.uid() or public.can_manage_content());
create policy "Admins can update profiles" on public.profiles
  for update to authenticated
  using (public.current_user_role() = 'admin')
  with check (public.current_user_role() = 'admin');

create policy "Published plants are public" on public.plant_species
  for select to anon, authenticated using (status = 'published' or public.can_manage_content());
create policy "Managers manage plants" on public.plant_species
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published taxonomy is public" on public.taxa
  for select to anon, authenticated using (
    exists (
      select 1 from public.species_taxa st
      join public.plant_species ps on ps.id = st.species_id
      where st.taxon_id = taxa.id and ps.status = 'published'
    ) or public.can_manage_content()
  );
create policy "Managers manage taxonomy" on public.taxa
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published species taxonomy links are public" on public.species_taxa
  for select to anon, authenticated using (
    exists (select 1 from public.plant_species ps where ps.id = species_id and ps.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage species taxonomy links" on public.species_taxa
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published morphology is public" on public.morphologies
  for select to anon, authenticated using (
    exists (select 1 from public.plant_species ps where ps.id = species_id and ps.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage morphology" on public.morphologies
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published physiology is public" on public.physiologies
  for select to anon, authenticated using (
    exists (select 1 from public.plant_species ps where ps.id = species_id and ps.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage physiology" on public.physiologies
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Observation locations are public" on public.locations
  for select to anon, authenticated using (true);
create policy "Managers manage locations" on public.locations
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published observations are public" on public.plant_observations
  for select to anon, authenticated using (
    exists (select 1 from public.plant_species ps where ps.id = species_id and ps.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage observations" on public.plant_observations
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published media is public" on public.media
  for select to anon, authenticated using (
    exists (select 1 from public.plant_species ps where ps.id = species_id and ps.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage media" on public.media
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published modules are public" on public.learning_modules
  for select to anon, authenticated using (status = 'published' or public.can_manage_content());
create policy "Managers manage modules" on public.learning_modules
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published lessons are public" on public.learning_lessons
  for select to anon, authenticated using (
    exists (select 1 from public.learning_modules lm where lm.id = module_id and lm.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage lessons" on public.learning_lessons
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published module species links are public" on public.module_species
  for select to anon, authenticated using (
    exists (select 1 from public.learning_modules lm where lm.id = module_id and lm.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage module species links" on public.module_species
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published quizzes are visible" on public.quizzes
  for select to authenticated using (status = 'published' or public.can_manage_content());
create policy "Managers manage quizzes" on public.quizzes
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published questions are visible" on public.questions
  for select to authenticated using (
    exists (select 1 from public.quizzes q where q.id = quiz_id and q.status = 'published')
    or public.can_manage_content()
  );
create policy "Managers manage questions" on public.questions
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Published question options are visible" on public.question_options
  for select to authenticated using (
    exists (
      select 1 from public.questions qn
      join public.quizzes q on q.id = qn.quiz_id
      where qn.id = question_id and q.status = 'published'
    ) or public.can_manage_content()
  );
create policy "Managers manage question options" on public.question_options
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Managers read answer keys" on public.question_keys
  for select to authenticated using (public.can_manage_content());
create policy "Managers manage answer keys" on public.question_keys
  for all to authenticated using (public.can_manage_content()) with check (public.can_manage_content());

create policy "Users read own attempts and managers read all" on public.quiz_attempts
  for select to authenticated using (user_id = auth.uid() or public.can_manage_content());
create policy "Students create own attempts" on public.quiz_attempts
  for insert to authenticated with check (user_id = auth.uid() and public.current_user_role() = 'mahasiswa');
create policy "Students update own attempts" on public.quiz_attempts
  for update to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());

create policy "Users read own answers and managers read all" on public.quiz_answers
  for select to authenticated using (
    exists (select 1 from public.quiz_attempts qa where qa.id = attempt_id and qa.user_id = auth.uid())
    or public.can_manage_content()
  );
create policy "Students manage own answers" on public.quiz_answers
  for all to authenticated
  using (exists (select 1 from public.quiz_attempts qa where qa.id = attempt_id and qa.user_id = auth.uid()))
  with check (exists (select 1 from public.quiz_attempts qa where qa.id = attempt_id and qa.user_id = auth.uid()));

create or replace function public.save_plant_species(
  p_plant_id bigint,
  p_payload jsonb,
  p_morphology jsonb,
  p_taxonomy jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  saved_id bigint;
  parent_taxon_id bigint := null;
  saved_taxon_id bigint;
  rank_name text;
  rank_value public.taxon_rank;
begin
  if not public.can_manage_content() then
    raise exception 'Akses ditolak';
  end if;

  if p_plant_id is null then
    insert into public.plant_species (
      code, slug, local_name, scientific_name, author_name, group_type,
      cotyledon_type, description, habitat, benefits, image_path, status
    ) values (
      upper(p_payload ->> 'code'), p_payload ->> 'slug', trim(p_payload ->> 'local_name'),
      trim(p_payload ->> 'scientific_name'), nullif(trim(p_payload ->> 'author_name'), ''),
      (p_payload ->> 'group_type')::public.group_type,
      (p_payload ->> 'cotyledon_type')::public.cotyledon_type,
      nullif(trim(p_payload ->> 'description'), ''), nullif(trim(p_payload ->> 'habitat'), ''),
      nullif(trim(p_payload ->> 'benefits'), ''), nullif(p_payload ->> 'image_path', ''),
      (p_payload ->> 'status')::public.publication_status
    ) returning id into saved_id;
  else
    update public.plant_species set
      code = upper(p_payload ->> 'code'),
      slug = p_payload ->> 'slug',
      local_name = trim(p_payload ->> 'local_name'),
      scientific_name = trim(p_payload ->> 'scientific_name'),
      author_name = nullif(trim(p_payload ->> 'author_name'), ''),
      group_type = (p_payload ->> 'group_type')::public.group_type,
      cotyledon_type = (p_payload ->> 'cotyledon_type')::public.cotyledon_type,
      description = nullif(trim(p_payload ->> 'description'), ''),
      habitat = nullif(trim(p_payload ->> 'habitat'), ''),
      benefits = nullif(trim(p_payload ->> 'benefits'), ''),
      image_path = nullif(p_payload ->> 'image_path', ''),
      status = (p_payload ->> 'status')::public.publication_status
    where id = p_plant_id
    returning id into saved_id;

    if saved_id is null then
      raise exception 'Spesimen tidak ditemukan';
    end if;
  end if;

  insert into public.morphologies (
    species_id, root, stem, leaf, flower, fruit, seed, special_characteristics
  ) values (
    saved_id, nullif(trim(p_morphology ->> 'root'), ''), nullif(trim(p_morphology ->> 'stem'), ''),
    nullif(trim(p_morphology ->> 'leaf'), ''), nullif(trim(p_morphology ->> 'flower'), ''),
    nullif(trim(p_morphology ->> 'fruit'), ''), nullif(trim(p_morphology ->> 'seed'), ''),
    nullif(trim(p_morphology ->> 'special_characteristics'), '')
  )
  on conflict (species_id) do update set
    root = excluded.root, stem = excluded.stem, leaf = excluded.leaf,
    flower = excluded.flower, fruit = excluded.fruit, seed = excluded.seed,
    special_characteristics = excluded.special_characteristics;

  delete from public.species_taxa where species_id = saved_id;

  foreach rank_name in array array['kingdom', 'divisi', 'kelas', 'ordo', 'famili', 'genus', 'spesies']
  loop
    if nullif(trim(p_taxonomy ->> rank_name), '') is not null then
      rank_value := rank_name::public.taxon_rank;
      insert into public.taxa (parent_id, name, rank)
      values (parent_taxon_id, trim(p_taxonomy ->> rank_name), rank_value)
      on conflict (rank, name) do update
        set parent_id = coalesce(public.taxa.parent_id, excluded.parent_id)
      returning id into saved_taxon_id;

      insert into public.species_taxa (species_id, taxon_id)
      values (saved_id, saved_taxon_id)
      on conflict do nothing;
      parent_taxon_id := saved_taxon_id;
    end if;
  end loop;

  return saved_id;
end;
$$;

create or replace function public.save_learning_module(
  p_module_id bigint,
  p_payload jsonb,
  p_lessons jsonb,
  p_species_ids bigint[]
)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  saved_id bigint;
  lesson jsonb;
begin
  if not public.can_manage_content() then
    raise exception 'Akses ditolak';
  end if;

  if jsonb_array_length(p_lessons) = 0 then
    raise exception 'Minimal satu subbab harus tersedia';
  end if;

  if p_module_id is null then
    insert into public.learning_modules (
      title, slug, description, module_order, estimated_minutes,
      chapter_summary, source_file, status
    ) values (
      trim(p_payload ->> 'title'), p_payload ->> 'slug', coalesce(trim(p_payload ->> 'description'), ''),
      (p_payload ->> 'module_order')::integer, (p_payload ->> 'estimated_minutes')::integer,
      coalesce(p_payload -> 'chapter_summary', '[]'::jsonb), nullif(p_payload ->> 'source_file', ''),
      (p_payload ->> 'status')::public.publication_status
    ) returning id into saved_id;
  else
    update public.learning_modules set
      title = trim(p_payload ->> 'title'),
      slug = p_payload ->> 'slug',
      description = coalesce(trim(p_payload ->> 'description'), ''),
      module_order = (p_payload ->> 'module_order')::integer,
      estimated_minutes = (p_payload ->> 'estimated_minutes')::integer,
      chapter_summary = coalesce(p_payload -> 'chapter_summary', '[]'::jsonb),
      source_file = nullif(p_payload ->> 'source_file', ''),
      status = (p_payload ->> 'status')::public.publication_status
    where id = p_module_id
    returning id into saved_id;

    if saved_id is null then
      raise exception 'Bab pembelajaran tidak ditemukan';
    end if;
  end if;

  delete from public.learning_lessons where module_id = saved_id;

  for lesson in select value from jsonb_array_elements(p_lessons)
  loop
    insert into public.learning_lessons (
      module_id, source_id, title, slug, content, content_format,
      key_points, source_sections, lesson_order
    ) values (
      saved_id, nullif(lesson ->> 'source_id', ''), trim(lesson ->> 'title'),
      lesson ->> 'slug', lesson ->> 'content', coalesce(lesson ->> 'content_format', 'markdown'),
      coalesce(lesson -> 'key_points', '[]'::jsonb), coalesce(lesson -> 'source_sections', '[]'::jsonb),
      (lesson ->> 'lesson_order')::integer
    );
  end loop;

  delete from public.module_species where module_id = saved_id;
  insert into public.module_species (module_id, species_id)
  select saved_id, species_id
  from unnest(coalesce(p_species_ids, array[]::bigint[])) as species_id;

  return saved_id;
end;
$$;

create or replace function public.start_quiz_attempt(p_quiz_id bigint)
returns bigint
language plpgsql
security invoker
set search_path = public
as $$
declare
  existing_id bigint;
begin
  if public.current_user_role() <> 'mahasiswa' then
    raise exception 'Hanya mahasiswa aktif yang dapat mengerjakan kuis';
  end if;

  if not exists (
    select 1 from public.quizzes q
    where q.id = p_quiz_id and q.status = 'published'
      and exists (select 1 from public.questions qn where qn.quiz_id = q.id)
  ) then
    raise exception 'Kuis belum tersedia atau belum memiliki soal';
  end if;

  select id into existing_id
  from public.quiz_attempts
  where user_id = auth.uid() and quiz_id = p_quiz_id and completed_at is null
  limit 1;

  if existing_id is not null then
    return existing_id;
  end if;

  insert into public.quiz_attempts (user_id, quiz_id)
  values (auth.uid(), p_quiz_id)
  returning id into existing_id;

  return existing_id;
end;
$$;

create or replace function public.submit_quiz_attempt(p_attempt_id bigint, p_answers jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  attempt_row public.quiz_attempts%rowtype;
  question_row public.questions%rowtype;
  selected_id bigint;
  answer_text text;
  correct boolean;
  total_weight integer := 0;
  earned_weight integer := 0;
  correct_count integer := 0;
  final_score integer := 0;
begin
  select * into attempt_row
  from public.quiz_attempts
  where id = p_attempt_id
  for update;

  if attempt_row.id is null or attempt_row.user_id <> auth.uid() then
    raise exception 'Percobaan kuis tidak ditemukan';
  end if;

  if attempt_row.completed_at is not null then
    raise exception 'Percobaan kuis sudah diselesaikan';
  end if;

  for question_row in
    select * from public.questions where quiz_id = attempt_row.quiz_id order by id
  loop
    total_weight := total_weight + question_row.score_weight;
    selected_id := null;
    answer_text := nullif(trim(p_answers ->> question_row.id::text), '');
    correct := false;

    if question_row.question_type in ('pilihan_ganda', 'multiple_choice', 'true_false')
       and answer_text ~ '^[0-9]+$' then
      selected_id := answer_text::bigint;
      select exists (
        select 1
        from public.question_options qo
        join public.question_keys qk on qk.correct_option_id = qo.id
        where qo.id = selected_id
          and qo.question_id = question_row.id
          and qk.question_id = question_row.id
      ) into correct;
    end if;

    if correct then
      earned_weight := earned_weight + question_row.score_weight;
      correct_count := correct_count + 1;
    end if;

    insert into public.quiz_answers (
      attempt_id, question_id, selected_option_id, essay_answer, is_correct
    ) values (
      attempt_row.id, question_row.id, selected_id,
      case when question_row.question_type = 'esai' then answer_text else null end,
      correct
    )
    on conflict (attempt_id, question_id) do update set
      selected_option_id = excluded.selected_option_id,
      essay_answer = excluded.essay_answer,
      is_correct = excluded.is_correct;
  end loop;

  if total_weight > 0 then
    final_score := round((earned_weight::numeric / total_weight::numeric) * 100)::integer;
  end if;

  update public.quiz_attempts
  set completed_at = now(), score = final_score, total_correct = correct_count
  where id = attempt_row.id;

  return jsonb_build_object(
    'attempt_id', attempt_row.id,
    'score', final_score,
    'total_correct', correct_count
  );
end;
$$;

create or replace function public.get_quiz_result(p_attempt_id bigint)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  attempt_row public.quiz_attempts%rowtype;
  quiz_row public.quizzes%rowtype;
  module_row public.learning_modules%rowtype;
  question_details jsonb;
begin
  select * into attempt_row from public.quiz_attempts where id = p_attempt_id;

  if attempt_row.id is null
     or (attempt_row.user_id <> auth.uid() and not public.can_manage_content()) then
    raise exception 'Hasil kuis tidak ditemukan';
  end if;

  if attempt_row.completed_at is null then
    raise exception 'Kuis belum diselesaikan';
  end if;

  select * into quiz_row from public.quizzes where id = attempt_row.quiz_id;
  select * into module_row from public.learning_modules where id = quiz_row.module_id;

  select coalesce(jsonb_agg(detail.item order by detail.question_id), '[]'::jsonb)
  into question_details
  from (
    select
      qn.id as question_id,
      jsonb_build_object(
        'question', to_jsonb(qn),
        'options', coalesce((
          select jsonb_agg(to_jsonb(qo) order by qo.id)
          from public.question_options qo
          where qo.question_id = qn.id
        ), '[]'::jsonb),
        'answer', (
          select to_jsonb(qa)
          from public.quiz_answers qa
          where qa.attempt_id = attempt_row.id and qa.question_id = qn.id
        ),
        'correct_option_id', (
          select qk.correct_option_id
          from public.question_keys qk
          where qk.question_id = qn.id
        )
      ) as item
    from public.questions qn
    where qn.quiz_id = quiz_row.id
  ) as detail;

  return jsonb_build_object(
    'attempt', to_jsonb(attempt_row),
    'quiz', to_jsonb(quiz_row),
    'module', to_jsonb(module_row),
    'questions', question_details
  );
end;
$$;

revoke all on function public.save_plant_species(bigint, jsonb, jsonb, jsonb) from public;
revoke all on function public.save_learning_module(bigint, jsonb, jsonb, bigint[]) from public;
revoke all on function public.start_quiz_attempt(bigint) from public;
revoke all on function public.submit_quiz_attempt(bigint, jsonb) from public;
revoke all on function public.get_quiz_result(bigint) from public;
grant execute on function public.save_plant_species(bigint, jsonb, jsonb, jsonb) to authenticated;
grant execute on function public.save_learning_module(bigint, jsonb, jsonb, bigint[]) to authenticated;
grant execute on function public.start_quiz_attempt(bigint) to authenticated;
grant execute on function public.submit_quiz_attempt(bigint, jsonb) to authenticated;
grant execute on function public.get_quiz_result(bigint) to authenticated;

create policy "Public storage objects are readable" on storage.objects
  for select to anon, authenticated
  using (
    bucket_id = (select value from public.app_settings where key = 'storage_bucket')
  );

create policy "Managers upload plant media" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = (select value from public.app_settings where key = 'storage_bucket')
    and public.can_manage_content()
  );

create policy "Managers update plant media" on storage.objects
  for update to authenticated
  using (
    bucket_id = (select value from public.app_settings where key = 'storage_bucket')
    and public.can_manage_content()
  )
  with check (
    bucket_id = (select value from public.app_settings where key = 'storage_bucket')
    and public.can_manage_content()
  );

create policy "Managers delete plant media" on storage.objects
  for delete to authenticated
  using (
    bucket_id = (select value from public.app_settings where key = 'storage_bucket')
    and public.can_manage_content()
  );

commit;
